dependencies:
    pre:
        - echo "date.timezone = Asia/Tokyo" > /opt/circleci/php/$(phpenv global)/etc/conf.d/date.ini
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    steps:
      - checkout
      - run: sudo apt-get install php7.0-intl
